name: Build and deploy Node.js app to Azure Web App - backendpresalessalereturns

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.20.4'
      
      - name: Install dependencies and build
        run: |
          npm install
          npm run build
          
      - name: Upload artifact for deployment
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: |
            dist/
            node_modules/
            package.json
            package-lock.json
            web.config
            swagger.yaml
            public/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: node-app
          
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_853882F080F54A33A2AB122D4E38A5D7 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_29994BBA45A04AA3A6CE7EBC234BC94D }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_5B4877B03E4C407D97BC8C0899011331 }}
          
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'backendpresalessalereturns'
          slot-name: 'Production'
          package: .
